# Generated by Django 5.0.14 on 2025-07-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField()),
            ],
        ),
    ]
