# Generated by Django 5.0.14 on 2025-07-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEG', '0003_b_c_d_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='F',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='J',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='K',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='L',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='O',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='R',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='U',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='W',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='X',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Y',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Z',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Å',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Æ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ø',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
    ]
