# Generated by Django 5.0.14 on 2025-07-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEG', '0004_f_g_h_i_j_k_l_m_n_o_p_q_r_s_t_u_v_w_x_y_z_å_æ_ø'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alfabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogstav', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
            ],
        ),
    ]
