# Generated by Django 5.0.14 on 2025-07-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEG', '0005_alfabet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bogstav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogstav', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='a',
            name='bogstav',
            field=models.ManyToManyField(related_name='item', to='LEG.bogstav'),
        ),
    ]
