# Generated by Django 5.0.14 on 2025-07-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEG', '0006_bogstav_a_bogstav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alfabet',
            name='bogstav',
        ),
        migrations.AddField(
            model_name='alfabet',
            name='beskrivelse',
            field=models.TextField(blank=True),
        ),
    ]
