# Generated by Django 5.0.14 on 2025-07-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEG', '0007_remove_alfabet_bogstav_alfabet_beskrivelse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a',
            name='bogstav',
        ),
        migrations.CreateModel(
            name='Ekstra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
                ('bogstav', models.ManyToManyField(related_name='item', to='LEG.bogstav')),
            ],
        ),
    ]
